package com.github.olavgg.grailsshop.initdata

import com.github.olavgg.grailsshop.money.CurrencyType

class CurrencyInitService {

    def init() {
        new CurrencyType('AED', 'United Arab Emirates Dirham').save(flush:true)
        new CurrencyType('AFN', 'Afghanistan Afghani').save(flush:true)
        new CurrencyType('ALL', 'Albania Lek').save(flush:true)
        new CurrencyType('AMD', 'Armenia Dram').save(flush:true)
        new CurrencyType('ANG', 'Netherlands Antilles Guilder').save(flush:true)
        new CurrencyType('AOA', 'Angola Kwanza').save(flush:true)
        new CurrencyType('ARS', 'Argentina Peso').save(flush:true)
        new CurrencyType('AUD', 'Australia Dollar').save(flush:true)
        new CurrencyType('AWG', 'Aruba Guilder').save(flush:true)
        new CurrencyType('AZN', 'Azerbaijan New Manat').save(flush:true)
        new CurrencyType('BAM', 'Bosnia and Herzegovina Convertible Marka').save(flush:true)
        new CurrencyType('BBD', 'Barbados Dollar').save(flush:true)
        new CurrencyType('BDT', 'Bangladesh Taka').save(flush:true)
        new CurrencyType('BGN', 'Bulgaria Lev').save(flush:true)
        new CurrencyType('BHD', 'Bahrain Dinar').save(flush:true)
        new CurrencyType('BIF', 'Burundi Franc').save(flush:true)
        new CurrencyType('BMD', 'Bermuda Dollar').save(flush:true)
        new CurrencyType('BND', 'Brunei Darussalam Dollar').save(flush:true)
        new CurrencyType('BOB', 'Bolivia Boliviano').save(flush:true)
        new CurrencyType('BRL', 'Brazil Real').save(flush:true)
        new CurrencyType('BSD', 'Bahamas Dollar').save(flush:true)
        new CurrencyType('BTN', 'Bhutan Ngultrum').save(flush:true)
        new CurrencyType('BWP', 'Botswana Pula').save(flush:true)
        new CurrencyType('BYR', 'Belarus Ruble').save(flush:true)
        new CurrencyType('BZD', 'Belize Dollar').save(flush:true)
        new CurrencyType('CAD', 'Canada Dollar').save(flush:true)
        new CurrencyType('CDF', 'Congo/Kinshasa Franc').save(flush:true)
        new CurrencyType('CHF', 'Switzerland Franc').save(flush:true)
        new CurrencyType('CLP', 'Chile Peso').save(flush:true)
        new CurrencyType('CNY', 'China Yuan Renminbi').save(flush:true)
        new CurrencyType('COP', 'Colombia Peso').save(flush:true)
        new CurrencyType('CRC', 'Costa Rica Colon').save(flush:true)
        new CurrencyType('CUC', 'Cuba Convertible Peso').save(flush:true)
        new CurrencyType('CUP', 'Cuba Peso').save(flush:true)
        new CurrencyType('CVE', 'Cape Verde Escudo').save(flush:true)
        new CurrencyType('CZK', 'Czech Republic Koruna').save(flush:true)
        new CurrencyType('DJF', 'Djibouti Franc').save(flush:true)
        new CurrencyType('DKK', 'Denmark Krone').save(flush:true)
        new CurrencyType('DOP', 'Dominican Republic Peso').save(flush:true)
        new CurrencyType('DZD', 'Algeria Dinar').save(flush:true)
        new CurrencyType('EGP', 'Egypt Pound').save(flush:true)
        new CurrencyType('ERN', 'Eritrea Nakfa').save(flush:true)
        new CurrencyType('ETB', 'Ethiopia Birr').save(flush:true)
        new CurrencyType('EUR', 'Euro Member Countries').save(flush:true)
        new CurrencyType('FJD', 'Fiji Dollar').save(flush:true)
        new CurrencyType('FKP', 'Falkland Islands (Malvinas) Pound').save(flush:true)
        new CurrencyType('GBP', 'United Kingdom Pound').save(flush:true)
        new CurrencyType('GEL', 'Georgia Lari').save(flush:true)
        new CurrencyType('GGP', 'Guernsey Pound').save(flush:true)
        new CurrencyType('GHS', 'Ghana Cedi').save(flush:true)
        new CurrencyType('GIP', 'Gibraltar Pound').save(flush:true)
        new CurrencyType('GMD', 'Gambia Dalasi').save(flush:true)
        new CurrencyType('GNF', 'Guinea Franc').save(flush:true)
        new CurrencyType('GTQ', 'Guatemala Quetzal').save(flush:true)
        new CurrencyType('GYD', 'Guyana Dollar').save(flush:true)
        new CurrencyType('HKD', 'Hong Kong Dollar').save(flush:true)
        new CurrencyType('HNL', 'Honduras Lempira').save(flush:true)
        new CurrencyType('HRK', 'Croatia Kuna').save(flush:true)
        new CurrencyType('HTG', 'Haiti Gourde').save(flush:true)
        new CurrencyType('HUF', 'Hungary Forint').save(flush:true)
        new CurrencyType('IDR', 'Indonesia Rupiah').save(flush:true)
        new CurrencyType('ILS', 'Israel Shekel').save(flush:true)
        new CurrencyType('IMP', 'Isle of Man Pound').save(flush:true)
        new CurrencyType('INR', 'India Rupee').save(flush:true)
        new CurrencyType('IQD', 'Iraq Dinar').save(flush:true)
        new CurrencyType('IRR', 'Iran Rial').save(flush:true)
        new CurrencyType('ISK', 'Iceland Krona').save(flush:true)
        new CurrencyType('JEP', 'Jersey Pound').save(flush:true)
        new CurrencyType('JMD', 'Jamaica Dollar').save(flush:true)
        new CurrencyType('JOD', 'Jordan Dinar').save(flush:true)
        new CurrencyType('JPY', 'Japan Yen').save(flush:true)
        new CurrencyType('KES', 'Kenya Shilling').save(flush:true)
        new CurrencyType('KGS', 'Kyrgyzstan Som').save(flush:true)
        new CurrencyType('KHR', 'Cambodia Riel').save(flush:true)
        new CurrencyType('KMF', 'Comoros Franc').save(flush:true)
        new CurrencyType('KPW', 'Korea (North) Won').save(flush:true)
        new CurrencyType('KRW', 'Korea (South) Won').save(flush:true)
        new CurrencyType('KWD', 'Kuwait Dinar').save(flush:true)
        new CurrencyType('KYD', 'Cayman Islands Dollar').save(flush:true)
        new CurrencyType('KZT', 'Kazakhstan Tenge').save(flush:true)
        new CurrencyType('LAK', 'Laos Kip').save(flush:true)
        new CurrencyType('LBP', 'Lebanon Pound').save(flush:true)
        new CurrencyType('LKR', 'Sri Lanka Rupee').save(flush:true)
        new CurrencyType('LRD', 'Liberia Dollar').save(flush:true)
        new CurrencyType('LSL', 'Lesotho Loti').save(flush:true)
        new CurrencyType('LTL', 'Lithuania Litas').save(flush:true)
        new CurrencyType('LVL', 'Latvia Lat').save(flush:true)
        new CurrencyType('LYD', 'Libya Dinar').save(flush:true)
        new CurrencyType('MAD', 'Morocco Dirham').save(flush:true)
        new CurrencyType('MDL', 'Moldova Leu').save(flush:true)
        new CurrencyType('MGA', 'Madagascar Ariary').save(flush:true)
        new CurrencyType('MKD', 'Macedonia Denar').save(flush:true)
        new CurrencyType('MMK', 'Myanmar (Burma) Kyat').save(flush:true)
        new CurrencyType('MNT', 'Mongolia Tughrik').save(flush:true)
        new CurrencyType('MOP', 'Macau Pataca').save(flush:true)
        new CurrencyType('MRO', 'Mauritania Ouguiya').save(flush:true)
        new CurrencyType('MUR', 'Mauritius Rupee').save(flush:true)
        new CurrencyType('MVR', 'Maldives (Maldive Islands) Rufiyaa').save(flush:true)
        new CurrencyType('MWK', 'Malawi Kwacha').save(flush:true)
        new CurrencyType('MXN', 'Mexico Peso').save(flush:true)
        new CurrencyType('MYR', 'Malaysia Ringgit').save(flush:true)
        new CurrencyType('MZN', 'Mozambique Metical').save(flush:true)
        new CurrencyType('NAD', 'Namibia Dollar').save(flush:true)
        new CurrencyType('NGN', 'Nigeria Naira').save(flush:true)
        new CurrencyType('NIO', 'Nicaragua Cordoba').save(flush:true)
        new CurrencyType('NOK', 'Norway Krone').save(flush:true)
        new CurrencyType('NPR', 'Nepal Rupee').save(flush:true)
        new CurrencyType('NZD', 'New Zealand Dollar').save(flush:true)
        new CurrencyType('OMR', 'Oman Rial').save(flush:true)
        new CurrencyType('PAB', 'Panama Balboa').save(flush:true)
        new CurrencyType('PEN', 'Peru Nuevo Sol').save(flush:true)
        new CurrencyType('PGK', 'Papua New Guinea Kina').save(flush:true)
        new CurrencyType('PHP', 'Philippines Peso').save(flush:true)
        new CurrencyType('PKR', 'Pakistan Rupee').save(flush:true)
        new CurrencyType('PLN', 'Poland Zloty').save(flush:true)
        new CurrencyType('PYG', 'Paraguay Guarani').save(flush:true)
        new CurrencyType('QAR', 'Qatar Riyal').save(flush:true)
        new CurrencyType('RON', 'Romania New Leu').save(flush:true)
        new CurrencyType('RSD', 'Serbia Dinar').save(flush:true)
        new CurrencyType('RUB', 'Russia Ruble').save(flush:true)
        new CurrencyType('RWF', 'Rwanda Franc').save(flush:true)
        new CurrencyType('SAR', 'Saudi Arabia Riyal').save(flush:true)
        new CurrencyType('SBD', 'Solomon Islands Dollar').save(flush:true)
        new CurrencyType('SCR', 'Seychelles Rupee').save(flush:true)
        new CurrencyType('SDG', 'Sudan Pound').save(flush:true)
        new CurrencyType('SEK', 'Sweden Krona').save(flush:true)
        new CurrencyType('SGD', 'Singapore Dollar').save(flush:true)
        new CurrencyType('SHP', 'Saint Helena Pound').save(flush:true)
        new CurrencyType('SLL', 'Sierra Leone Leone').save(flush:true)
        new CurrencyType('SOS', 'Somalia Shilling').save(flush:true)
        new CurrencyType('SPL*', 'Seborga Luigino').save(flush:true)
        new CurrencyType('SRD', 'Suriname Dollar').save(flush:true)
        new CurrencyType('STD', 'São Tomé and Príncipe Dobra').save(flush:true)
        new CurrencyType('SVC', 'El Salvador Colon').save(flush:true)
        new CurrencyType('SYP', 'Syria Pound').save(flush:true)
        new CurrencyType('SZL', 'Swaziland Lilangeni').save(flush:true)
        new CurrencyType('THB', 'Thailand Baht').save(flush:true)
        new CurrencyType('TJS', 'Tajikistan Somoni').save(flush:true)
        new CurrencyType('TMT', 'Turkmenistan Manat').save(flush:true)
        new CurrencyType('TND', 'Tunisia Dinar').save(flush:true)
        new CurrencyType('TOP', 'Tonga Pa\'anga').save(flush:true)
        new CurrencyType('TRY', 'Turkey Lira').save(flush:true)
        new CurrencyType('TTD', 'Trinidad and Tobago Dollar').save(flush:true)
        new CurrencyType('TVD', 'Tuvalu Dollar').save(flush:true)
        new CurrencyType('TWD', 'Taiwan New Dollar').save(flush:true)
        new CurrencyType('TZS', 'Tanzania Shilling').save(flush:true)
        new CurrencyType('UAH', 'Ukraine Hryvna').save(flush:true)
        new CurrencyType('UGX', 'Uganda Shilling').save(flush:true)
        new CurrencyType('USD', 'United States Dollar').save(flush:true)
        new CurrencyType('UYU', 'Uruguay Peso').save(flush:true)
        new CurrencyType('UZS', 'Uzbekistan Som').save(flush:true)
        new CurrencyType('VEF', 'Venezuela Bolivar').save(flush:true)
        new CurrencyType('VND', 'Viet Nam Dong').save(flush:true)
        new CurrencyType('VUV', 'Vanuatu Vatu').save(flush:true)
        new CurrencyType('WST', 'Samoa Tala').save(flush:true)
        new CurrencyType('XAF', 'Communauté Financière Africaine (BEAC) CFA Franc BEAC').save(flush:true)
        new CurrencyType('XCD', 'East Caribbean Dollar').save(flush:true)
        new CurrencyType('XDR', 'International Monetary Fund (IMF) Special Drawing Rights').save(flush:true)
        new CurrencyType('XOF', 'Communauté Financière Africaine (BCEAO) Franc').save(flush:true)
        new CurrencyType('XPF', 'Comptoirs Français du Pacifique (CFP) Franc').save(flush:true)
        new CurrencyType('YER', 'Yemen Rial').save(flush:true)
        new CurrencyType('ZAR', 'South Africa Rand').save(flush:true)
        new CurrencyType('ZMW', 'Zambia Kwacha').save(flush:true)
        new CurrencyType('ZWD', 'Zimbabwe Dollar').save(flush:true)
    }
}
